# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


locale: "en-US"
title: Relative Absolutes
author:
  name: Matt Velez
  email: matt@mattvelez.net
  avatar: /assets/images/matt.jpg
  bio: Raconteur.
  location: Pennsylvania, USA
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/timecrash"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/maserspark"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/timecrash"
description: >- # this means to ignore newlines until "baseurl:"
  I'm Matt Velez, a writer currently living in the Philadelphia suburbs.
  Back in 2012, I figured out writing was a heck of a lot more fun than everyone let on, and I’ve been doing it ever since.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mattvelez.net" # the base hostname & protocol for your site, e.g. http://example.com

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/timecrash"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/maserspark"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/timecrash"

# Build settings
#theme: minima
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: neon
repository: Timecrash/relative_absolutes
permalink: /:categories/:title/
timezone: America/New_York
search: true
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
whitelist:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
include: 
  - CNAME
  - assets/images

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      share: true
      related: true
      classes: wide

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
