locale: "en-US"
title: Relative Absolutes
author:
  name: Matt Velez
  email: matt@mattvelez.net
  avatar: /assets/images/matt.jpg
  bio: Raconteur.
  location: Pennsylvania, USA
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/timecrash"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://wandering.shop/@timecrash"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/maserspark"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/timecrash"
description: >-
  I'm Matt Velez, a writer currently living in the Philadelphia suburbs.
  Back in 2012, I figured out writing was a heck of a lot more fun than everyone let on, and I've been doing it ever since.
baseurl: ""
url: "https://mattvelez.net"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/timecrash"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://wandering.shop/@timecrash"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/maserspark"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/timecrash"

# Build settings
#theme: minima
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: neon
repository: Timecrash/relative_absolutes
permalink: /:categories/:title
timezone: America/New_York
search: true
breadcrumbs: true
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
whitelist:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
include:
  - CNAME
twitter:
  username: "timecrash"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      share: true
      related: true
      classes: wide

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
